name: Playwright QA Automation

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm init -y
          npm install playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: 22f3000965@ds.study.iitm.ac.in - Run Scraper
        run: node scrape.js
